{% set name = "lunarcalendar-ext" %}
{% set version = "0.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/LunarCalendar-ext-{{ version }}.tar.gz
  sha256: e9afee2869e131b8a0c1d23dc067232b78c52f97dcf3d00b239eea867d398d2c
  patches:
    - 0001-add-version-var.patch

build:
  skip: True  # [py==312 or s390x or (py>39 and arm64)]
  number: 0
  entry_points:
    - lunar-find=lunarcalendar.command:find
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - patch  # [not win]
    - m2-patch  # [win]
  host:
    - pip
    - python
    - wheel
  run:
    - ephem >=3.7.5.3  # [not arm64]
    - ephem 3.7.7  # [arm64]
    - python
    - python-dateutil >=2.6.1
    - pytz

test:
  source_files:
    - tests
  imports:
    - lunarcalendar
  commands:
    - pip check
    - set PYTHONUTF8=1
    - lunar-find --help
    - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/KaixuYang/LunarCalendar-extension
  summary: A bugfix fork of LunarCalendar, a Lunar-Solar calendar converter.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: This repo forks the [LunarCalendar](https://github.com/wolfhong/LunarCalendar) repo and fixes some bugs.
  dev_url: https://github.com/KaixuYang/LunarCalendar-extension
  doc_url: https://github.com/wolfhong/LunarCalendar/blob/master/README.rst

extra:
  recipe-maintainers:
    - thewchan
